name: MyMaid4
version: ${project.version}
main: com.jaoafa.mymaid4.Main
api-version: 1.16
author: mine_book000
database: true
description: Our "Maid" is here.
website: https://jaoafa.com
softdepend:
  - PermissionsEx
  - LuckPerms
  - GeoipAPI
  - dynmap
  - Votifier
  - jaoSuperAchievement
  - MinecraftJPVoteMissFiller
  - ViaVersion
  - LunaChat
